#!/bin/python3

from pathlib import Path
from socket import socket, AF_UNIX, SOCK_STREAM
import sys

this_dir = Path(__file__).parent
socket_path = this_dir / "sql-creds.sock"

client = socket(AF_UNIX, SOCK_STREAM)
client.connect(socket_path.as_posix())
response = client.recv(2048) # Arbitrary max receive value

if len(response) == 0:
	print("Access denied.", file=sys.stderr)
	sys.exit(1)
else:
	print(response.decode(encoding='utf-8'))
